// Copyright (c) Aniket Malik [aniketmalikwork@gmail.com]
// All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the
// property of Aniket Malik. The intellectual and technical concepts
// contained herein are proprietary to Aniket Malik and are protected
// by trade secret or copyright law.
//
// Dissemination of this information or reproduction of this material
// is strictly forbidden unless prior written permission is obtained from
// Aniket Malik.

// DO NOT EDIT THIS FILE OR ELSE YOUR APPLICATION'S FUNCTIONALITY COULD BREAK

const Map<String, dynamic> $__defaultAppTemplateMap__$ = {
  'id': 123456789,
  'name': 'WooStore Pro',
  'appConfigurationData': {
    'currency': 'USD',
    'currencySymbol': '\$',
    'placeholderImageUrl': 'https://via.placeholder.com/100',
    'contactUsUrl': 'https://example.com',
    'contactUsPhone': '+000000000000',
    'contactUsEmail': 'support@example.com',
    'termsOfServiceUrl': 'https://example.com',
    'privacyPolicyUrl': 'https://example.com',
    'shareAppLink': 'https://example.com',
    'shareAppImageUrl': 'https://via.placeholder.com/100',
    'enableShareAppThroughFirebaseDynamicLinks': true,
    'appFirebaseConfigurationData': {
      'uriPrefix': 'https://example.page.link',
      'androidPackageName': 'com.example.android.app',
      'iOSBundleId': 'com.example.ios.app',
      'appStoreId': '0',
      'isEnabledForSharingProducts': true,
      'shareProductTitle': true,
      'shareProductDescription': true,
      'shareProductImage': true
    },
    'firebaseNotificationTopics': ['Version Update Available', 'Promotions'],
    'showTagsInSearchFilterModal': true,
    'showTagsInAllProductsFilterModal': true,
    'showCustomerDownloadsListTile': true,
    'enablePointsAndRewardsSupport': false,
    'showPointsListTile': false,
    'showPointsInProductScreen': false,
    'enabledVariationSwatchesForWooCommerce': true,
    'enableGuestCheckout': true
  },
  'appThemes': {
    'lightThemeData': {
      'primaryColor': 'FF20c4f4',
      'onPrimaryColor': 'FFFFFFFF',
      'secondaryColor': 'FF8191dd',
      'onSecondaryColor': 'FFFFFFFF',
      'errorColor': 'FFEC3B15',
      'onErrorColor': 'FFFFFFFF',
      'scaffoldBackgroundColor': 'FFEEEEEE',
      'backgroundColor': 'FFFFFFFF',
      'appBarThemeData': {
        'backgroundColor': 'FFEEEEEE',
        'elevation': 0.0,
        'textStyleData': {
          'fontSize': 20.0,
          'fontWeight': 6.0,
          'color': '',
          'alignment': null
        },
        'iconStyleData': {'fontSize': 24.0, 'color': ''}
      }
    },
    'darkThemeData': {
      'primaryColor': 'FF20c4f4',
      'onPrimaryColor': 'FFFFFFFF',
      'secondaryColor': 'FF8191dd',
      'onSecondaryColor': 'FFFFFFFF',
      'errorColor': 'FFEC3B15',
      'onErrorColor': 'FFFFFFFF',
      'scaffoldBackgroundColor': 'FF161616',
      'backgroundColor': 'FF0A0A0A',
      'appBarThemeData': {
        'backgroundColor': 'FF161616',
        'elevation': 0.0,
        'textStyleData': {
          'fontSize': 20.0,
          'fontWeight': 6.0,
          'color': '',
          'alignment': null
        },
        'iconStyleData': {'fontSize': 24.0, 'color': ''}
      }
    }
  },
  'appScreens': [
    {
      'id': 25,
      'name': 'Product Details',
      'appScreenLayoutType': 'product',
      'screenType': 'preBuilt',
      'screenLayout': 'expandable',
      'bottomButtonsLayout': 'layout2',
      'sections': [
        {
          'id': 1,
          'sectionType': 'image',
          'styledData': {
            'paddingData': {
              'left': 0.0,
              'top': 0.0,
              'right': 0.0,
              'bottom': 0.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'aspectRatio': 1.0,
          'showImageGallery': false
        },
        {
          'id': 5,
          'sectionType': 'productName',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 16.0,
              'fontWeight': 6.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          }
        },
        {
          'id': 6,
          'sectionType': 'price',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'sectionLayout': 'layout1'
        },
        {
          'id': 7,
          'sectionType': 'pointsAndRewards',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          }
        },
        {
          'id': 8,
          'sectionType': 'vendor',
          'styledData': {
            'paddingData': {
              'left': 0.0,
              'top': 0.0,
              'right': 0.0,
              'bottom': 0.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 16.0,
              'fontWeight': 6.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 500.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'sectionLayout': 'originalWithBanner',
          'aspectRatio': 2.0
        },
        {
          'id': 9,
          'sectionType': 'stockAvailability',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'sectionLayout': 'layout1'
        },
        {
          'id': 10,
          'sectionType': 'shortDescription',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'expanded': false,
          'showTitle': true
        },
        {
          'id': 11,
          'sectionType': 'attributes',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'sectionLayout': 'layout1'
        },
        {
          'id': 12,
          'sectionType': 'quantity',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'sectionLayout': 'layout1'
        },
        {
          'id': 13,
          'sectionType': 'description',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'expanded': false,
          'showTitle': true
        },
        {
          'id': 14,
          'sectionType': 'review',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'sectionLayout': 'layout1'
        },
        {
          'id': 15,
          'sectionType': 'categories',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'itemListConfig': {
            'itemPadding': 5.0,
            'listType': 'list',
            'gridColumn': 2,
            'aspectRatio': 1.0
          },
          'showTitle': true
        },
        {
          'id': 16,
          'sectionType': 'tags',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'itemListConfig': {
            'itemPadding': 5.0,
            'listType': 'list',
            'gridColumn': 2,
            'aspectRatio': 1.0
          },
          'showTitle': true
        },
        {
          'id': 2,
          'sectionType': 'text',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'text': 'Some Awesome text',
          'action': {'type': 'noAction'}
        },
        {
          'id': 3,
          'sectionType': 'banner',
          'styledData': {
            'paddingData': {
              'left': 0.0,
              'top': 0.0,
              'right': 0.0,
              'bottom': 0.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'imageUrl': '',
          'action': {'type': 'noAction'}
        },
        {
          'id': 4,
          'sectionType': 'advancedBanner',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'showNewLabel': false,
          'heading': '',
          'headingTextStyleData': {
            'fontSize': 28.0,
            'fontWeight': 6.0,
            'color': '',
            'alignment': null
          },
          'imageBorderRadius': 0.0,
          'imageUrl': '',
          'description': '',
          'bottomDescription': '',
          'actionButtonText': '',
          'action': {'type': 'noAction'},
          'itemImageBoxFit': 'cover'
        },
        {
          'id': 17,
          'sectionType': 'upSellProducts',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'productListConfig': {
            'layoutData': {
              'layoutType': 'vertical',
              'width': 225.0,
              'height': 355.0,
              'sections': [
                {
                  'show': true,
                  'sectionType': 'image',
                  'height': 236.66666666666666,
                  'width': 225.0,
                  'borderRadius': 10.0,
                  'showRating': true,
                  'showLikeButton': true,
                  'showAddToCartButton': true,
                  'boxFit': 'cover'
                },
                {
                  'show': true,
                  'sectionType': 'name',
                  'marginData': {
                    'left': 10.0,
                    'top': 5.0,
                    'right': 10.0,
                    'bottom': 5.0
                  },
                  'textStyleData': {
                    'fontSize': 16.0,
                    'fontWeight': 5.0,
                    'color': '',
                    'alignment': null
                  }
                },
                {
                  'show': true,
                  'sectionType': 'price',
                  'marginData': {
                    'left': 10.0,
                    'top': 5.0,
                    'right': 10.0,
                    'bottom': 5.0
                  },
                  'textStyleData': {
                    'fontSize': 14.0,
                    'fontWeight': 5.0,
                    'color': '',
                    'alignment': null
                  }
                },
                {
                  'show': true,
                  'sectionType': 'rating',
                  'marginData': {
                    'left': 10.0,
                    'top': 5.0,
                    'right': 10.0,
                    'bottom': 5.0
                  },
                  'textStyleData': {
                    'fontSize': 12.0,
                    'fontWeight': 5.0,
                    'color': '',
                    'alignment': null
                  },
                  'iconSize': 12.0,
                  'iconColor': '#555500'
                }
              ],
              'backgroundColor': '',
              'borderRadius': 10.0
            },
            'itemPadding': 5.0,
            'useGlobalProductCardLayout': true,
            'listType': 'list',
            'gridColumn': 2
          }
        },
        {
          'id': 18,
          'sectionType': 'crossSellProducts',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'productListConfig': {
            'layoutData': {
              'layoutType': 'vertical',
              'width': 225.0,
              'height': 355.0,
              'sections': [
                {
                  'show': true,
                  'sectionType': 'image',
                  'height': 236.66666666666666,
                  'width': 225.0,
                  'borderRadius': 10.0,
                  'showRating': true,
                  'showLikeButton': true,
                  'showAddToCartButton': true,
                  'boxFit': 'cover'
                },
                {
                  'show': true,
                  'sectionType': 'name',
                  'marginData': {
                    'left': 10.0,
                    'top': 5.0,
                    'right': 10.0,
                    'bottom': 5.0
                  },
                  'textStyleData': {
                    'fontSize': 16.0,
                    'fontWeight': 5.0,
                    'color': '',
                    'alignment': null
                  }
                },
                {
                  'show': true,
                  'sectionType': 'price',
                  'marginData': {
                    'left': 10.0,
                    'top': 5.0,
                    'right': 10.0,
                    'bottom': 5.0
                  },
                  'textStyleData': {
                    'fontSize': 14.0,
                    'fontWeight': 5.0,
                    'color': '',
                    'alignment': null
                  }
                },
                {
                  'show': true,
                  'sectionType': 'rating',
                  'marginData': {
                    'left': 10.0,
                    'top': 5.0,
                    'right': 10.0,
                    'bottom': 5.0
                  },
                  'textStyleData': {
                    'fontSize': 12.0,
                    'fontWeight': 5.0,
                    'color': '',
                    'alignment': null
                  },
                  'iconSize': 12.0,
                  'iconColor': '#555500'
                }
              ],
              'backgroundColor': '',
              'borderRadius': 10.0
            },
            'itemPadding': 5.0,
            'useGlobalProductCardLayout': true,
            'listType': 'list',
            'gridColumn': 2
          }
        },
        {
          'id': 19,
          'sectionType': 'relatedProducts',
          'styledData': {
            'paddingData': {
              'left': 15.0,
              'top': 15.0,
              'right': 15.0,
              'bottom': 15.0
            },
            'marginData': {
              'left': 10.0,
              'top': 0.0,
              'right': 10.0,
              'bottom': 10.0
            },
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': null
            },
            'backgroundColor': '',
            'borderRadius': 10.0,
            'dimensionsData': {
              'height': 150.0,
              'width': 150.0,
              'aspectRatio': 1.0
            },
            'imageBoxFit': 'cover'
          },
          'productListConfig': {
            'layoutData': {
              'layoutType': 'vertical',
              'width': 225.0,
              'height': 355.0,
              'sections': [
                {
                  'show': true,
                  'sectionType': 'image',
                  'height': 236.66666666666666,
                  'width': 225.0,
                  'borderRadius': 10.0,
                  'showRating': true,
                  'showLikeButton': true,
                  'showAddToCartButton': true,
                  'boxFit': 'cover'
                },
                {
                  'show': true,
                  'sectionType': 'name',
                  'marginData': {
                    'left': 10.0,
                    'top': 5.0,
                    'right': 10.0,
                    'bottom': 5.0
                  },
                  'textStyleData': {
                    'fontSize': 16.0,
                    'fontWeight': 5.0,
                    'color': '',
                    'alignment': null
                  }
                },
                {
                  'show': true,
                  'sectionType': 'price',
                  'marginData': {
                    'left': 10.0,
                    'top': 5.0,
                    'right': 10.0,
                    'bottom': 5.0
                  },
                  'textStyleData': {
                    'fontSize': 14.0,
                    'fontWeight': 5.0,
                    'color': '',
                    'alignment': null
                  }
                },
                {
                  'show': true,
                  'sectionType': 'rating',
                  'marginData': {
                    'left': 10.0,
                    'top': 5.0,
                    'right': 10.0,
                    'bottom': 5.0
                  },
                  'textStyleData': {
                    'fontSize': 12.0,
                    'fontWeight': 5.0,
                    'color': '',
                    'alignment': null
                  },
                  'iconSize': 12.0,
                  'iconColor': '#555500'
                }
              ],
              'backgroundColor': '',
              'borderRadius': 10.0
            },
            'itemPadding': 5.0,
            'useGlobalProductCardLayout': true,
            'listType': 'list',
            'gridColumn': 2
          }
        }
      ],
      'appBarData': {
        'title': '',
        'logo': '',
        'leading': {
          'id': 0,
          'iconData': {
            'codePoint': 60282,
            'fontFamily': 'EvaIcons',
            'fontPackage': 'eva_icons_flutter'
          },
          'tooltip': '',
          'action': {'type': 'noAction'},
          'color': '',
          'size': 24.0,
          'allowDelete': true,
          'allowChangeAction': true,
          'hidden': true
        },
        'actionButtons': [
          {
            'id': 1,
            'iconData': {
              'codePoint': 60151,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter'
            },
            'tooltip': 'Like',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': false,
            'allowChangeAction': false,
            'hidden': false
          },
          {
            'id': 3,
            'iconData': {
              'codePoint': 63526,
              'fontFamily': 'MaterialIcons',
              'fontPackage': ''
            },
            'tooltip': 'Share',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': false,
            'allowChangeAction': false,
            'hidden': false
          },
          {
            'id': 2,
            'iconData': {
              'codePoint': 60318,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter'
            },
            'tooltip': 'Cart',
            'action': {
              'type': 'navigation',
              'navigationData': {'screenId': 2, 'screenName': 'Cart'},
              'args': null
            },
            'color': '',
            'size': 24.0,
            'allowDelete': true,
            'allowChangeAction': true,
            'hidden': false
          }
        ],
        'centerTitle': false,
        'pinned': false,
        'floating': true,
        'show': true
      },
      'bottomButtonTextStyle': {
        'fontSize': 14.0,
        'fontWeight': 5.0,
        'color': '',
        'alignment': null
      }
    },
    {
      'id': 11,
      'name': 'All Products',
      'appScreenLayoutType': 'allProducts',
      'screenType': 'preBuilt',
      'appBarData': {
        'title': '',
        'logo': '',
        'leading': {
          'id': 0,
          'iconData': {
            'codePoint': 60282,
            'fontFamily': 'EvaIcons',
            'fontPackage': 'eva_icons_flutter'
          },
          'tooltip': '',
          'action': {'type': 'noAction'},
          'color': '',
          'size': 24.0,
          'allowDelete': true,
          'allowChangeAction': true,
          'hidden': true
        },
        'actionButtons': [
          {
            'id': 1,
            'iconData': {
              'codePoint': 60229,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter'
            },
            'tooltip': 'Filters',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': false,
            'allowChangeAction': false,
            'hidden': false
          },
          {
            'id': 3,
            'iconData': {
              'codePoint': 57984,
              'fontFamily': 'MaterialIcons',
              'fontPackage': ''
            },
            'tooltip': 'Sort',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': false,
            'allowChangeAction': false,
            'hidden': false
          }
        ],
        'centerTitle': false,
        'pinned': false,
        'floating': true,
        'show': true
      },
      'productListConfig': {
        'layoutData': {
          'layoutType': 'vertical',
          'width': 225.0,
          'height': 340.0,
          'sections': [
            {
              'show': true,
              'sectionType': 'image',
              'height': 236.66666666666666,
              'width': 225.0,
              'borderRadius': 10.0,
              'showRating': true,
              'showLikeButton': true,
              'showAddToCartButton': true,
              'boxFit': 'cover'
            },
            {
              'show': true,
              'sectionType': 'name',
              'marginData': {
                'left': 10.0,
                'top': 5.0,
                'right': 10.0,
                'bottom': 5.0
              },
              'textStyleData': {
                'fontSize': 16.0,
                'fontWeight': 5.0,
                'color': '',
                'alignment': null
              }
            },
            {
              'show': true,
              'sectionType': 'price',
              'marginData': {
                'left': 10.0,
                'top': 5.0,
                'right': 10.0,
                'bottom': 5.0
              },
              'textStyleData': {
                'fontSize': 14.0,
                'fontWeight': 5.0,
                'color': '',
                'alignment': null
              }
            },
            {
              'show': true,
              'sectionType': 'rating',
              'marginData': {
                'left': 10.0,
                'top': 5.0,
                'right': 10.0,
                'bottom': 5.0
              },
              'textStyleData': {
                'fontSize': 12.0,
                'fontWeight': 5.0,
                'color': '',
                'alignment': null
              },
              'iconSize': 12.0,
              'iconColor': '#555500'
            }
          ],
          'backgroundColor': '',
          'borderRadius': 10.0
        },
        'itemPadding': 5.0,
        'useGlobalProductCardLayout': false,
        'listType': 'grid',
        'gridColumn': 2
      }
    },
    {
      'id': 10,
      'name': 'On Boarding',
      'appScreenLayoutType': 'onBoarding',
      'screenType': 'preBuilt',
      'pages': [
        {
          'id': 1,
          'titleData': {
            'label': 'Shop all that you want',
            'textStyleData': {
              'fontSize': 16.0,
              'fontWeight': 6.0,
              'color': '',
              'alignment': null
            }
          },
          'descriptionData': {
            'label':
                'You get a wide variety of products all just a few clicks away! Hurry get them all',
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': 'center'
            }
          },
          'assetData': {
            'path': '',
            'height': 200.0,
            'width': 200.0,
            'boxFit': 'cover',
            'allowFullWidth': true,
            'type': 'undefined'
          }
        },
        {
          'id': 2,
          'titleData': {
            'label': 'Easy shopping experience',
            'textStyleData': {
              'fontSize': 16.0,
              'fontWeight': 6.0,
              'color': '',
              'alignment': null
            }
          },
          'descriptionData': {
            'label':
                'No hassle, just a few clicks and the product is in your house in a few days',
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': 'center'
            }
          },
          'assetData': {
            'path': '',
            'height': 200.0,
            'width': 200.0,
            'boxFit': 'cover',
            'allowFullWidth': true,
            'type': 'undefined'
          }
        },
        {
          'id': 3,
          'titleData': {
            'label': 'Easy Checkouts',
            'textStyleData': {
              'fontSize': 16.0,
              'fontWeight': 6.0,
              'color': '',
              'alignment': null
            }
          },
          'descriptionData': {
            'label':
                'Just choose the delivery option and we will take care of the rest',
            'textStyleData': {
              'fontSize': 14.0,
              'fontWeight': 5.0,
              'color': '',
              'alignment': 'center'
            }
          },
          'assetData': {
            'path': '',
            'height': 200.0,
            'width': 200.0,
            'boxFit': 'cover',
            'allowFullWidth': true,
            'type': 'undefined'
          }
        }
      ]
    },
    {
      'id': 2,
      'name': 'Cart',
      'appScreenLayoutType': 'cart',
      'screenType': 'preBuilt',
      'appBarData': {
        'title': '',
        'logo': '',
        'leading': {
          'id': 0,
          'iconData': {
            'codePoint': 60282,
            'fontFamily': 'EvaIcons',
            'fontPackage': 'eva_icons_flutter'
          },
          'tooltip': '',
          'action': {'type': 'noAction'},
          'color': '',
          'size': 24.0,
          'allowDelete': true,
          'allowChangeAction': true,
          'hidden': true
        },
        'actionButtons': [
          {
            'id': 1,
            'iconData': {
              'codePoint': 983273,
              'fontFamily': 'MaterialIcons',
              'fontPackage': ''
            },
            'tooltip': 'Reload',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': false,
            'allowChangeAction': false,
            'hidden': false
          }
        ],
        'centerTitle': false,
        'pinned': false,
        'floating': true,
        'show': true
      },
      'enableNativeCheckout': true,
      'enableCoupon': true,
      'enableCustomerNote': true,
      'couponData': {
        'layout': 'original',
        'showUsageLimit': true,
        'showUsageCount': true,
        'showCouponType': true,
        'showMinimumSpend': true,
        'showMaximumSpend': true
      }
    },
    {
      'id': 1,
      'name': 'Category',
      'appScreenLayoutType': 'category',
      'screenType': 'preBuilt',
      'appBarData': {
        'title': '',
        'logo': '',
        'leading': {
          'id': 0,
          'iconData': {
            'codePoint': 60282,
            'fontFamily': 'EvaIcons',
            'fontPackage': 'eva_icons_flutter'
          },
          'tooltip': '',
          'action': {'type': 'noAction'},
          'color': '',
          'size': 24.0,
          'allowDelete': true,
          'allowChangeAction': true,
          'hidden': true
        },
        'actionButtons': [],
        'centerTitle': false,
        'pinned': false,
        'floating': true,
        'show': true
      },
      'layout': 'grid',
      'columns': 3,
      'hideItemImage': false,
      'itemStyledData': {
        'paddingData': {'left': 5.0, 'top': 5.0, 'right': 5.0, 'bottom': 5.0},
        'marginData': {'left': 5.0, 'top': 5.0, 'right': 5.0, 'bottom': 5.0},
        'textStyleData': {
          'fontSize': 14.0,
          'fontWeight': 5.0,
          'color': '',
          'alignment': null
        },
        'backgroundColor': '',
        'borderRadius': 10.0,
        'dimensionsData': {'height': 150.0, 'width': 150.0, 'aspectRatio': 0.8},
        'imageBoxFit': 'cover'
      }
    },
    {
      'id': 8,
      'name': 'My Account',
      'appScreenLayoutType': 'myAccount',
      'screenType': 'preBuilt',
      'sections': [
        {
          'id': 8,
          'show': true,
          'type': 'myPoints',
          'name': 'My Points',
          'iconData': {'pack': 'material', 'key': 'post_add_rounded'},
          'editIcon': true
        },
        {
          'id': 9,
          'show': true,
          'type': 'downloads',
          'name': 'Downloads',
          'iconData': {
            'pack': 'custom',
            'iconData': {
              'codePoint': 60080,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter',
              'matchTextDirection': false
            }
          },
          'editIcon': true
        },
        {
          'id': 10,
          'show': true,
          'type': 'shippingAddress',
          'name': 'Shipping Address',
          'iconData': {'pack': 'material', 'key': 'local_shipping'},
          'editIcon': true
        },
        {
          'id': 11,
          'show': true,
          'type': 'billingAddress',
          'name': 'Billing Address',
          'iconData': {'pack': 'material', 'key': 'credit_card_rounded'},
          'editIcon': true
        },
        {
          'id': 12,
          'show': true,
          'type': 'changePassword',
          'name': 'Change Password',
          'iconData': {'pack': 'material', 'key': 'security'},
          'editIcon': true
        },
        {
          'id': 19,
          'show': true,
          'type': 'logout',
          'name': 'Login/Logout',
          'iconData': {'pack': 'material', 'key': 'login'},
          'editIcon': false
        }
      ],
      'appBarData': {
        'title': '',
        'logo': '',
        'leading': {
          'id': 0,
          'iconData': {
            'codePoint': 60282,
            'fontFamily': 'EvaIcons',
            'fontPackage': 'eva_icons_flutter'
          },
          'tooltip': '',
          'action': {'type': 'noAction'},
          'color': '',
          'size': 24.0,
          'allowDelete': true,
          'allowChangeAction': true,
          'hidden': true
        },
        'actionButtons': [],
        'centerTitle': false,
        'pinned': false,
        'floating': true,
        'show': true
      }
    },
    {
      'id': 7,
      'name': 'My Orders',
      'appScreenLayoutType': 'myOrders',
      'screenType': 'preBuilt',
      'appBarData': {
        'title': '',
        'logo': '',
        'leading': {
          'id': 0,
          'iconData': {
            'codePoint': 60282,
            'fontFamily': 'EvaIcons',
            'fontPackage': 'eva_icons_flutter'
          },
          'tooltip': '',
          'action': {'type': 'noAction'},
          'color': '',
          'size': 24.0,
          'allowDelete': true,
          'allowChangeAction': true,
          'hidden': true
        },
        'actionButtons': [],
        'centerTitle': false,
        'pinned': false,
        'floating': true,
        'show': true
      }
    },
    {
      'id': 9,
      'name': 'Setting',
      'appScreenLayoutType': 'setting',
      'screenType': 'preBuilt',
      'sections': [
        {
          'id': 13,
          'show': true,
          'type': 'languages',
          'name': 'Languages',
          'iconData': {'pack': 'material', 'key': 'language_rounded'},
          'editIcon': true
        },
        {
          'id': 14,
          'show': true,
          'type': 'contactUs',
          'name': 'Contact Us',
          'iconData': {'pack': 'material', 'key': 'call'},
          'editIcon': true
        },
        {
          'id': 15,
          'show': true,
          'type': 'termsOfService',
          'name': 'Terms of service',
          'iconData': {
            'pack': 'material',
            'key': 'miscellaneous_services_rounded'
          },
          'editIcon': true
        },
        {
          'id': 16,
          'show': true,
          'type': 'privacyPolicy',
          'name': 'Privacy Policy',
          'iconData': {'pack': 'material', 'key': 'lock'},
          'editIcon': true
        },
        {
          'id': 17,
          'show': true,
          'type': 'shareApp',
          'name': 'Share App',
          'iconData': {'pack': 'material', 'key': 'share'},
          'editIcon': false
        },
        {
          'id': 18,
          'show': true,
          'type': 'aboutUs',
          'name': 'About Us',
          'iconData': {'pack': 'material', 'key': 'info_outline_rounded'},
          'editIcon': true
        }
      ],
      'appBarData': {
        'title': '',
        'logo': '',
        'leading': {
          'id': 0,
          'iconData': {
            'codePoint': 60282,
            'fontFamily': 'EvaIcons',
            'fontPackage': 'eva_icons_flutter'
          },
          'tooltip': '',
          'action': {'type': 'noAction'},
          'color': '',
          'size': 24.0,
          'allowDelete': true,
          'allowChangeAction': true,
          'hidden': true
        },
        'actionButtons': [],
        'centerTitle': false,
        'pinned': false,
        'floating': true,
        'show': true
      }
    },
    {
      'id': 3,
      'name': 'Profile',
      'appScreenLayoutType': 'profile',
      'screenType': 'preBuilt',
      'sections': [
        {
          'id': 1,
          'show': true,
          'type': 'myOrders',
          'name': 'My Orders',
          'iconData': {
            'pack': 'custom',
            'iconData': {
              'codePoint': 60157,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter',
              'matchTextDirection': false
            }
          },
          'editIcon': true
        },
        {
          'id': 2,
          'show': true,
          'type': 'wishlist',
          'name': 'Wishlist',
          'iconData': {
            'pack': 'custom',
            'iconData': {
              'codePoint': 60150,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter',
              'matchTextDirection': false
            }
          },
          'editIcon': true
        },
        {
          'id': 3,
          'show': true,
          'type': 'profileInformation',
          'name': 'Profile Information',
          'iconData': {'pack': 'material', 'key': 'verified_user'},
          'editIcon': true
        },
        {
          'id': 4,
          'show': true,
          'type': 'notifications',
          'name': 'Notifications',
          'iconData': {
            'pack': 'material',
            'key': 'notifications_active_rounded'
          },
          'editIcon': true
        },
        {
          'id': 5,
          'show': true,
          'type': 'account',
          'name': 'Account',
          'iconData': {'pack': 'material', 'key': 'account_box'},
          'editIcon': true
        },
        {
          'id': 6,
          'show': true,
          'type': 'settings',
          'name': 'Settings',
          'iconData': {
            'pack': 'custom',
            'iconData': {
              'codePoint': 60303,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter',
              'matchTextDirection': false
            }
          },
          'editIcon': true
        },
        {
          'id': 7,
          'show': true,
          'type': 'darkMode',
          'name': 'Dark Mode',
          'iconData': {'pack': 'material', 'key': 'color_lens'},
          'editIcon': true
        }
      ],
      'appBarData': {
        'title': '',
        'logo': '',
        'leading': {
          'id': 0,
          'iconData': {
            'codePoint': 60282,
            'fontFamily': 'EvaIcons',
            'fontPackage': 'eva_icons_flutter'
          },
          'tooltip': '',
          'action': {'type': 'noAction'},
          'color': '',
          'size': 24.0,
          'allowDelete': true,
          'allowChangeAction': true,
          'hidden': true
        },
        'actionButtons': [],
        'centerTitle': false,
        'pinned': false,
        'floating': true,
        'show': true
      }
    },
    {
      'id': 22,
      'name': 'Tags',
      'appScreenLayoutType': 'tags',
      'screenType': 'preBuilt',
      'appBarData': {
        'title': '',
        'logo': '',
        'leading': {
          'id': 0,
          'iconData': {
            'codePoint': 60282,
            'fontFamily': 'EvaIcons',
            'fontPackage': 'eva_icons_flutter'
          },
          'tooltip': '',
          'action': {'type': 'noAction'},
          'color': '',
          'size': 24.0,
          'allowDelete': true,
          'allowChangeAction': true,
          'hidden': true
        },
        'actionButtons': [],
        'centerTitle': false,
        'pinned': false,
        'floating': true,
        'show': true
      },
      'layout': 'grid',
      'columns': 2,
      'itemStyledData': {
        'paddingData': {
          'left': 15.0,
          'top': 15.0,
          'right': 15.0,
          'bottom': 15.0
        },
        'marginData': {'left': 5.0, 'top': 5.0, 'right': 5.0, 'bottom': 5.0},
        'textStyleData': {
          'fontSize': 14.0,
          'fontWeight': 5.0,
          'color': '',
          'alignment': null
        },
        'backgroundColor': '',
        'borderRadius': 10.0,
        'dimensionsData': {'height': 50.0, 'width': 150.0, 'aspectRatio': 2.0},
        'imageBoxFit': 'cover'
      }
    },
    {
      'id': 23,
      'name': 'Vendor',
      'appScreenLayoutType': 'vendor',
      'screenType': 'preBuilt',
      'appBarData': {
        'title': '',
        'logo': '',
        'leading': {
          'id': 0,
          'iconData': {
            'codePoint': 60282,
            'fontFamily': 'EvaIcons',
            'fontPackage': 'eva_icons_flutter'
          },
          'tooltip': '',
          'action': {'type': 'noAction'},
          'color': '',
          'size': 24.0,
          'allowDelete': true,
          'allowChangeAction': true,
          'hidden': true
        },
        'actionButtons': [
          {
            'id': 1,
            'iconData': {
              'codePoint': 60229,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter'
            },
            'tooltip': 'Filters',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': false,
            'allowChangeAction': false,
            'hidden': false
          },
          {
            'id': 2,
            'iconData': {
              'codePoint': 57984,
              'fontFamily': 'MaterialIcons',
              'fontPackage': ''
            },
            'tooltip': 'Sort',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': false,
            'allowChangeAction': false,
            'hidden': false
          },
          {
            'id': 3,
            'iconData': {
              'codePoint': 63509,
              'fontFamily': 'MaterialIcons',
              'fontPackage': ''
            },
            'tooltip': 'Info',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': false,
            'allowChangeAction': false,
            'hidden': false
          }
        ],
        'centerTitle': false,
        'pinned': false,
        'floating': true,
        'show': true
      },
      'productListConfig': {
        'layoutData': {
          'layoutType': 'vertical',
          'width': 225.0,
          'height': 355.0,
          'sections': [
            {
              'show': true,
              'sectionType': 'image',
              'height': 236.66666666666666,
              'width': 225.0,
              'borderRadius': 10.0,
              'showRating': true,
              'showLikeButton': true,
              'showAddToCartButton': true,
              'boxFit': 'cover'
            },
            {
              'show': true,
              'sectionType': 'name',
              'marginData': {
                'left': 10.0,
                'top': 5.0,
                'right': 10.0,
                'bottom': 5.0
              },
              'textStyleData': {
                'fontSize': 16.0,
                'fontWeight': 5.0,
                'color': '',
                'alignment': null
              }
            },
            {
              'show': true,
              'sectionType': 'price',
              'marginData': {
                'left': 10.0,
                'top': 5.0,
                'right': 10.0,
                'bottom': 5.0
              },
              'textStyleData': {
                'fontSize': 14.0,
                'fontWeight': 5.0,
                'color': '',
                'alignment': null
              }
            },
            {
              'show': true,
              'sectionType': 'rating',
              'marginData': {
                'left': 10.0,
                'top': 5.0,
                'right': 10.0,
                'bottom': 5.0
              },
              'textStyleData': {
                'fontSize': 12.0,
                'fontWeight': 5.0,
                'color': '',
                'alignment': null
              },
              'iconSize': 12.0,
              'iconColor': '#555500'
            }
          ],
          'backgroundColor': '',
          'borderRadius': 10.0
        },
        'itemPadding': 5.0,
        'useGlobalProductCardLayout': true,
        'listType': 'grid',
        'gridColumn': 2
      }
    },
    {
      'id': 24,
      'name': 'All Vendors',
      'appScreenLayoutType': 'allVendors',
      'screenType': 'preBuilt',
      'appBarData': {
        'title': '',
        'logo': '',
        'leading': {
          'id': 0,
          'iconData': {
            'codePoint': 60282,
            'fontFamily': 'EvaIcons',
            'fontPackage': 'eva_icons_flutter'
          },
          'tooltip': '',
          'action': {'type': 'noAction'},
          'color': '',
          'size': 24.0,
          'allowDelete': true,
          'allowChangeAction': true,
          'hidden': true
        },
        'actionButtons': [
          {
            'id': 1,
            'iconData': {
              'codePoint': 60229,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter'
            },
            'tooltip': 'Filters',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': false,
            'allowChangeAction': false,
            'hidden': false
          },
          {
            'id': 3,
            'iconData': {
              'codePoint': 57984,
              'fontFamily': 'MaterialIcons',
              'fontPackage': ''
            },
            'tooltip': 'Sort',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': false,
            'allowChangeAction': false,
            'hidden': false
          }
        ],
        'centerTitle': false,
        'pinned': false,
        'floating': true,
        'show': true
      },
      'itemListConfig': {
        'itemPadding': 10.0,
        'listType': 'grid',
        'gridColumn': 2,
        'aspectRatio': 0.7
      },
      'vendorCardLayoutData': {
        'styledData': {
          'paddingData': {'left': 0.0, 'top': 0.0, 'right': 0.0, 'bottom': 0.0},
          'marginData': {'left': 0.0, 'top': 0.0, 'right': 0.0, 'bottom': 0.0},
          'textStyleData': {
            'fontSize': 14.0,
            'fontWeight': 5.0,
            'color': '',
            'alignment': null
          },
          'backgroundColor': '',
          'borderRadius': 10.0,
          'dimensionsData': {
            'height': 150.0,
            'width': 150.0,
            'aspectRatio': 1.0
          },
          'imageBoxFit': 'cover'
        },
        'layoutType': 'originalWithBanner',
        'showRating': true
      }
    }
  ],
  'appTabs': [
    {
      'id': 1,
      'name': 'Home',
      'appScreenData': {
        'id': 1,
        'name': 'Dynamic',
        'appScreenLayoutType': 'dynamic',
        'screenType': 'custom',
        'appBarData': {
          'title': 'Profile Build Test',
          'logo': '',
          'leading': {
            'id': 0,
            'iconData': {
              'codePoint': 60282,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter'
            },
            'tooltip': '',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': true,
            'allowChangeAction': true,
            'hidden': true
          },
          'actionButtons': [
            {
              'id': 1,
              'iconData': {
                'codePoint': 983078,
                'fontFamily': 'MaterialIcons',
                'fontPackage': ''
              },
              'tooltip': 'Notification',
              'action': {
                'type': 'navigation',
                'navigationData': {'screenId': 6, 'screenName': 'Notification'},
                'args': null
              },
              'color': '',
              'size': 24.0,
              'allowDelete': true,
              'allowChangeAction': true,
              'hidden': false
            },
            {
              'id': 2,
              'iconData': {
                'codePoint': 60318,
                'fontFamily': 'EvaIcons',
                'fontPackage': 'eva_icons_flutter'
              },
              'tooltip': 'Cart',
              'action': {
                'type': 'navigation',
                'navigationData': {'screenId': 2, 'screenName': 'Cart'},
                'args': null
              },
              'color': '',
              'size': 24.0,
              'allowDelete': true,
              'allowChangeAction': true,
              'hidden': false
            }
          ],
          'centerTitle': false,
          'pinned': false,
          'floating': true,
          'show': true
        },
        'sections': []
      },
      'iconData': {
        'pack': 'custom',
        'iconData': {
          'codePoint': 60153,
          'fontFamily': 'EvaIcons',
          'fontPackage': 'eva_icons_flutter',
          'matchTextDirection': false
        }
      },
      'activeIconData': {
        'pack': 'custom',
        'iconData': {
          'codePoint': 60152,
          'fontFamily': 'EvaIcons',
          'fontPackage': 'eva_icons_flutter',
          'matchTextDirection': false
        }
      }
    },
    {
      'id': 2,
      'name': 'Category',
      'appScreenData': {
        'id': 2,
        'name': 'Category',
        'appScreenLayoutType': 'category',
        'screenType': 'custom',
        'appBarData': {
          'title': '',
          'logo': '',
          'leading': {
            'id': 0,
            'iconData': {
              'codePoint': 60282,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter'
            },
            'tooltip': '',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': true,
            'allowChangeAction': true,
            'hidden': true
          },
          'actionButtons': [],
          'centerTitle': false,
          'pinned': false,
          'floating': true,
          'show': true
        },
        'layout': 'grid',
        'columns': 3,
        'hideItemImage': false,
        'itemStyledData': {
          'paddingData': {'left': 5.0, 'top': 5.0, 'right': 5.0, 'bottom': 5.0},
          'marginData': {'left': 5.0, 'top': 5.0, 'right': 5.0, 'bottom': 5.0},
          'textStyleData': {
            'fontSize': 14.0,
            'fontWeight': 5.0,
            'color': '',
            'alignment': null
          },
          'backgroundColor': '',
          'borderRadius': 10.0,
          'dimensionsData': {
            'height': 150.0,
            'width': 150.0,
            'aspectRatio': 0.8
          },
          'imageBoxFit': 'cover'
        }
      },
      'iconData': {
        'pack': 'custom',
        'iconData': {
          'codePoint': 60143,
          'fontFamily': 'EvaIcons',
          'fontPackage': 'eva_icons_flutter',
          'matchTextDirection': false
        }
      },
      'activeIconData': {
        'pack': 'custom',
        'iconData': {
          'codePoint': 60142,
          'fontFamily': 'EvaIcons',
          'fontPackage': 'eva_icons_flutter',
          'matchTextDirection': false
        }
      }
    },
    {
      'id': 3,
      'name': 'Search',
      'appScreenData': {
        'id': 3,
        'name': 'Search',
        'appScreenLayoutType': 'search',
        'screenType': 'custom'
      },
      'iconData': {
        'pack': 'custom',
        'iconData': {
          'codePoint': 60302,
          'fontFamily': 'EvaIcons',
          'fontPackage': 'eva_icons_flutter',
          'matchTextDirection': false
        }
      },
      'activeIconData': {
        'pack': 'custom',
        'iconData': {
          'codePoint': 60301,
          'fontFamily': 'EvaIcons',
          'fontPackage': 'eva_icons_flutter',
          'matchTextDirection': false
        }
      }
    },
    {
      'id': 4,
      'name': 'Cart',
      'appScreenData': {
        'id': 4,
        'name': 'Cart',
        'appScreenLayoutType': 'cart',
        'screenType': 'custom',
        'appBarData': {
          'title': '',
          'logo': '',
          'leading': {
            'id': 0,
            'iconData': {
              'codePoint': 60282,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter'
            },
            'tooltip': '',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': true,
            'allowChangeAction': true,
            'hidden': true
          },
          'actionButtons': [
            {
              'id': 1,
              'iconData': {
                'codePoint': 983273,
                'fontFamily': 'MaterialIcons',
                'fontPackage': ''
              },
              'tooltip': 'Reload',
              'action': {'type': 'noAction'},
              'color': '',
              'size': 24.0,
              'allowDelete': false,
              'allowChangeAction': false,
              'hidden': false
            }
          ],
          'centerTitle': false,
          'pinned': false,
          'floating': true,
          'show': true
        },
        'enableNativeCheckout': true,
        'enableCoupon': true,
        'enableCustomerNote': true,
        'couponData': {
          'layout': 'original',
          'showUsageLimit': true,
          'showUsageCount': true,
          'showCouponType': true,
          'showMinimumSpend': true,
          'showMaximumSpend': true
        }
      },
      'iconData': {
        'pack': 'custom',
        'iconData': {
          'codePoint': 60318,
          'fontFamily': 'EvaIcons',
          'fontPackage': 'eva_icons_flutter',
          'matchTextDirection': false
        }
      },
      'activeIconData': {
        'pack': 'custom',
        'iconData': {
          'codePoint': 60317,
          'fontFamily': 'EvaIcons',
          'fontPackage': 'eva_icons_flutter',
          'matchTextDirection': false
        }
      }
    },
    {
      'id': 5,
      'name': 'Profile',
      'appScreenData': {
        'id': 5,
        'name': 'Profile',
        'appScreenLayoutType': 'profile',
        'screenType': 'custom',
        'sections': [
          {
            'id': 2,
            'show': true,
            'type': 'wishlist',
            'name': 'Wishlist',
            'iconData': {
              'pack': 'custom',
              'iconData': {
                'codePoint': 60150,
                'fontFamily': 'EvaIcons',
                'fontPackage': 'eva_icons_flutter',
                'matchTextDirection': false
              }
            },
            'editIcon': true
          },
          {
            'id': 3,
            'show': true,
            'type': 'profileInformation',
            'name': 'Profile Information',
            'iconData': {'pack': 'material', 'key': 'verified_user'},
            'editIcon': true
          },
          {
            'id': 4,
            'show': true,
            'type': 'notifications',
            'name': 'Notifications',
            'iconData': {
              'pack': 'material',
              'key': 'notifications_active_rounded'
            },
            'editIcon': true
          },
          {
            'id': 5,
            'show': true,
            'type': 'account',
            'name': 'Account',
            'iconData': {'pack': 'material', 'key': 'account_box'},
            'editIcon': true
          },
          {
            'id': 6,
            'show': true,
            'type': 'settings',
            'name': 'Settings',
            'iconData': {
              'pack': 'custom',
              'iconData': {
                'codePoint': 60303,
                'fontFamily': 'EvaIcons',
                'fontPackage': 'eva_icons_flutter',
                'matchTextDirection': false
              }
            },
            'editIcon': true
          },
          {
            'id': 7,
            'show': true,
            'type': 'darkMode',
            'name': 'Dark Mode',
            'iconData': {'pack': 'material', 'key': 'color_lens'},
            'editIcon': true
          }
        ],
        'appBarData': {
          'title': '',
          'logo': '',
          'leading': {
            'id': 0,
            'iconData': {
              'codePoint': 60282,
              'fontFamily': 'EvaIcons',
              'fontPackage': 'eva_icons_flutter'
            },
            'tooltip': '',
            'action': {'type': 'noAction'},
            'color': '',
            'size': 24.0,
            'allowDelete': true,
            'allowChangeAction': true,
            'hidden': true
          },
          'actionButtons': [],
          'centerTitle': false,
          'pinned': false,
          'floating': true,
          'show': false
        }
      },
      'iconData': {
        'pack': 'custom',
        'iconData': {
          'codePoint': 60247,
          'fontFamily': 'EvaIcons',
          'fontPackage': 'eva_icons_flutter',
          'matchTextDirection': false
        }
      },
      'activeIconData': {
        'pack': 'custom',
        'iconData': {
          'codePoint': 60240,
          'fontFamily': 'EvaIcons',
          'fontPackage': 'eva_icons_flutter',
          'matchTextDirection': false
        }
      }
    }
  ],
  'globalProductCardLayout': {
    'layoutType': 'vertical',
    'width': 225.0,
    'height': 355.0,
    'sections': [
      {
        'show': true,
        'sectionType': 'image',
        'height': 236.66666666666666,
        'width': 225.0,
        'borderRadius': 10.0,
        'showRating': true,
        'showLikeButton': true,
        'showAddToCartButton': true,
        'boxFit': 'cover'
      },
      {
        'show': true,
        'sectionType': 'name',
        'marginData': {'left': 10.0, 'top': 5.0, 'right': 10.0, 'bottom': 5.0},
        'textStyleData': {
          'fontSize': 16.0,
          'fontWeight': 5.0,
          'color': '',
          'alignment': null
        }
      },
      {
        'show': true,
        'sectionType': 'price',
        'marginData': {'left': 10.0, 'top': 5.0, 'right': 10.0, 'bottom': 5.0},
        'textStyleData': {
          'fontSize': 14.0,
          'fontWeight': 5.0,
          'color': '',
          'alignment': null
        }
      },
      {
        'show': true,
        'sectionType': 'rating',
        'marginData': {'left': 10.0, 'top': 5.0, 'right': 10.0, 'bottom': 5.0},
        'textStyleData': {
          'fontSize': 12.0,
          'fontWeight': 5.0,
          'color': '',
          'alignment': null
        },
        'iconSize': 12.0,
        'iconColor': '#555500'
      }
    ],
    'backgroundColor': '',
    'borderRadius': 10.0
  },
  'globalLoadingIconData': {'color': '', 'size': 0.0, 'type': 'spinKitWave'},
  'socialLoginData': {
    'enableAppleLogin': true,
    'enableGoogleLogin': true,
    'enableFacebookLogin': true,
    'enableSmsLogin': true,
    'defaultCountryCode': 'IN'
  },
  'metaData': {
    'createdTimeStamp': 1654250735743,
    'lastModified': 1656007084448,
    'displayImage': ''
  }
};
